name: kiosk_ai_core
description: Core IA services (NLP, Voice, Vision) for kiosk_ai, open-source on Linux
version: 0.1.0
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^3.8.3
  speech_to_text: ^6.6.0
  camera: ^0.10.6
  google_mlkit_object_detection: ^0.12.0
